import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Dank Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Dank Mono"
style = "Italic"

[font.normal]
family = "Dank Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.9

[window.padding]
x = 6
y = 6
