# Neutral daytime profile
profile {
    time = 07:00
    identity = true
}

# Gradually warm up through the evening
profile {
    time = 20:00
    temperature = 2630
}

profile {
    time = 21:00
    temperature = 2200
}

profile {
    time = 22:00
    temperature = 1800
}

profile {
    time = 23:00
    temperature = 1400
}

profile {
    time = 00:00
    temperature = 1000
}
