# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Shift+Shift
  # To enable, uncomment kb_layout and the grp option below:
  kb_layout = es
  kb_options = compose:caps # ,grp:shifts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  # sensitivity = 0.35

  # Turn off mouse acceleration (default: false)
  # force_no_accel = true

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4

    # Enable the touchpad while typing
    # disable_while_typing = false

    # Left-click-and-drag with three fingers
    # drag_3fg = 1
  }
}

# Scroll nicely in the terminal
windowrule = scroll_touchpad 1.5, match:class (Alacritty|kitty)
windowrule = scroll_touchpad 0.2, match:class com.mitchellh.ghostty

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace

# Enable touchpad gestures for moving focus (helpful on scrolling layout)
# gesture = 3, left,  dispatcher, movefocus, l
# gesture = 3, right, dispatcher, movefocus, r
