vim.keymap.set("n", "gd", "<cmd>call VSCodeNotify('editor.action.goToDeclaration')<CR>")
vim.keymap.set("n", "gr", "<cmd>call VSCodeNotify('editor.action.referenceSearch.trigger')<CR>")
vim.keymap.set("n", "<leader>rn", "<cmd>call VSCodeNotify('editor.action.rename')<CR>")
vim.keymap.set("n", "<leader>ca", "<cmd>call VSCodeNotify('editor.action.quickFix')<CR>")
vim.keymap.set("n", "<c-o>", "<cmd>call VSCodeNotify('workbench.action.navigateBack')<CR>")
vim.keymap.set("n", "<c-i>", "<cmd>call VSCodeNotify('workbench.action.navigateForward')<CR>")
-- vim.keymap.set("n", "<c-n>", "<cmd>call VSCodeNotify('workbench.action.nextEditorInGroup')<CR>")
-- vim.keymap.set("n", "<c-p>", "<cmd>call VSCodeNotify('workbench.action.previousEditorInGroup')<CR>")
vim.keymap.set("n", "K", "<cmd>call VSCodeNotify('editor.action.showHover')<CR>")
