theme = "catppuccin_frappe"

[editor]
mouse = true
bufferline = "multiple" # buffers as tabs

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-base-name", "file-modification-indicator"]
right = ["diagnostics", "position"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-c = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
C-q = ":buffer-close"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
K = "hover"
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
space.c = "toggle_comments"
space.space = "command_palette"
space.f.f = "file_picker"
space.f.s = "global_search"
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.insert]
C-c = [ "normal_mode" ] # https://github.com/helix-editor/helix/issues/822#issuecomment-1622621574
C-s = [ "normal_mode", ":w" ]

[keys.select]
C-c = "normal_mode"

