set nocompatible
filetype off
" line numbers
set number
" search files subdirectories
set path+=**
" allow tab to autocomplete searching files
set wildmenu
set wildignore+=**/node_modules/**
set wildignore+=**/cache/**
set wildignore+=**/logs/**
" vimplug
call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter' " Git-themes diff
Plug 'vim-airline/vim-airline' " Status bar
Plug 'vim-airline/vim-airline-themes' " Status bar themes
Plug 'terryma/vim-multiple-cursors' " Find all and edit
Plug 'haya14busa/incsearch.vim' " Search feedback
Plug 'fxn/vim-monochrome' " Grayscale theme
Plug 'mileszs/ack.vim' " Find in all project
call plug#end()
" prevent not-working delete key
set backspace=indent,eol,start
" paste from other applications without messing the indent
set paste
" airline
set laststatus=2
let g:airline_theme='light'
" allow per project settings
set exrc
set secure
" COMMANDS
"" set tab to be 4
command! Tab4 set tabstop=4 shiftwidth=4 softtabstop=4 expandtab smartindent autoindent
command! MakeTags !ctags -R . --exclude=.git --exclude=cache --exclude=logs
" SNIPPETS
"" Html template
nnoremap ,html :-1read $HOME/.vim/.skeleton.html<CR>2jwf>a
" Remap keys
nnoremap ] <C-]> 
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
" syntax and colors
syntax on
color monochrome
" tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smartindent
set smarttab
set autoindent
