"
" Some general settings
"

set nocompatible
filetype plugin indent on
syntax on

""""" I never change these
set ttyfast lazyredraw incsearch hlsearch ignorecase smartcase cursorline hidden autoread linebreak number mouse=a encoding=utf-8 backspace=indent,eol,start

""""" Sometimes I change these
set noshowmode                 " Don't show the mode you're in
" set relativenumber             " I will regret it (see...)
set scrolloff=3                " Spacing on top and bottom
set laststatus=2               " Hide bottom status line
set shortmess+=I               " Don't show :intro
try
  set signcolumn=number        " Show line numbers and signs on the same column"
catch
  set signcolumn=yes           " Fallback for older versions
endtry
set expandtab shiftround smartindent autoindent " Indent stuff

"
" Key mapping
"

" Remap leader key
let mapleader = "\<space>"

" Disable Ex Mode
nmap Q <Nop>

" Ctrl+c is ESC (it is by default but it won't trigger autocommands)
imap <c-c> <esc>

" Ctrl+hjkl moves split focus
nmap <c-h> <c-w>h
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-l> <c-w>l

" Use + to select all word matches
nmap + *N

" Ctrl+t new tab
nmap <c-t> :tabe<cr>

" Ctrl+q close buffer
nmap <c-q> :bd<cr>


" Ctrl+s to save
nmap <c-s> :w<cr>

" Format file
nmap <silent> <leader><Tab> :CocCommand tsserver.executeAutofix \| CocCommand prettier.formatFile<cr>
vmap <silent> <leader><Tab> <Plug>(coc-format-selected)
xmap <silent> <leader><Tab> <Plug>(coc-format-selected)

" Open terminal
nmap <leader>t :terminal<cr>

" Open .vimrc
nmap <leader>v :e ~/.vimrc<cr>

" Use system clipboard (reg *)
nmap <leader>cp "*y
vmap <leader>cp "*y
nmap <leader>p "*p
vmap <leader>p "*p

" Y should not be the same as yy
nmap Y y$

" Navigate buffers
" nmap <leader><leader> :ls<CR>:b<Space>
nmap <leader><leader> :CtrlPBuffer<cr>
nmap gb :bprev<cr>
nmap gn :bnext<cr>

" Disable arrow keys
nmap <Up> <Nop>
nmap <Down> <Nop>
nmap <Left> <Nop>
nmap <Right> <Nop>

" Easier block indentation
nnoremap > >>
nnoremap < <<
vnoremap > >gv
vnoremap < <gv
" ctrl+i is mapped to Tab so is not the opposite of ctrl+o anymore

" Search and replace in file/line (selection or word)
vnoremap <c-n> "9y:%s/<c-r>9/<c-r>9/g<left><left>
nnoremap <c-n> viw"9y:%s/<c-r>9/<c-r>9/g<left><left>
vnoremap <leader>n "9y:s/<c-r>9/<c-r>9/g<left><left>
nnoremap <leader>n viw"9y:s/<c-r>9/<c-r>9/g<left><left>

" Map ESC key to exit insert mode in :terminal (vim8 or neovim)
if has('terminal') || has('nvim')
  tmap <Esc> <C-\><C-n>
endif

" Identify the syntax group of the word at the cursor
nmap <leader>H :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
      \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
      \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

" Remove highlights
nmap <silent> <leader>h :noh<cr>

"
" Autocommands
"

" I don't wanna save changes to a directory ¬¬
autocmd FileType netrw setl bufhidden=delete

augroup templates
  autocmd!
  autocmd BufNewFile *.tsx,*.jsx
    \ 0r $HOME/.config/nvim/templates/react.tsx |
    \ exe "normal /template\<cr>diw"
  autocmd BufNewFile *_document.*
    \ 0r $HOME/.config/nvim/templates/_document.tsx
  autocmd BufNewFile *.json
    \ 0r $HOME/.config/nvim/templates/empty.json |
    \ exe "normal ggo"
augroup end

augroup LuaHighlight
  autocmd!
  autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank()
augroup END

"
" Abbreviations
"
iabbr widht width
iabbr heigth height
iabbr lenght length
iabbr ligth light
iabbr rigth right
iabbr ireact import React from 'react'
iabbr fcreact const Component = () =>
iabbr ccreact class Component extends React.Component

"
" PLUGINS. VimPlug will download and install all of them
"

" Start plugins
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive' " git tools
command! Conflicts Gvdiffsplit!
nnoremap <leader>dh :diffget //2<cr>
nnoremap <leader>dl :diffget //3<cr>
Plug 'tpope/vim-rhubarb' " for Gbrowse
Plug 'tpope/vim-repeat' " repeat more things with .
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-sensible' " nice defaults for vim
Plug 'pablopunk/native-sidebar.vim' " ctrl+b to open dir drawer
Plug 'ap/vim-buftabline' " show buffers as tabs
Plug 'mhinz/vim-startify' " show screen with shortcuts when opening vim
let g:startify_change_to_vcs_root = 1
let g:startify_change_to_dir = 0
Plug 'pablopunk/better-grep.vim' " ctrl+f to search words
" Plug 'pablopunk/better-find.vim'
Plug 'ctrlpvim/ctrlp.vim'
if executable('fd')
    let g:ctrlp_user_command = 'fd --type f --color never "" %s'
    let g:ctrlp_use_caching = 0
endif
Plug 'christoomey/vim-tmux-navigator' " enable ctrl+hjkl to navigate on tmux/vim
Plug 'pablopunk/persistent-undo.vim' " undo works across vim sessions
Plug 'pablopunk/hot-reload.vim', { 'for': 'vim' } " reload config when changing vimrc
Plug 'tpope/vim-commentary' " gcc for commenting
Plug 'tpope/vim-surround' " new vim action (cs=change surround) (ys=add surround) *requires a motion
Plug 'markonm/traces.vim' " to show in real time what your :s commands will replace
Plug 'sheerun/vim-polyglot' " lots of languages support in 1 plugin
Plug 'pablopunk/sick.vim'
Plug 'pablopunk/sunset.vim'
Plug 'morhetz/gruvbox'
Plug 'arzg/vim-colors-xcode'
Plug 'joshdick/onedark.vim'
Plug 'bluz71/vim-nightfly-guicolors'
Plug 'jcherven/jummidark.vim'
Plug 'zefei/simple-dark'
Plug 'arcticicestudio/nord-vim'
Plug 'pablopunk/transparent.vim'
" Plug 'pablopunk/statusline.vim'
Plug 'itchyny/lightline.vim'
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
Plug 'edkolev/tmuxline.vim' " To generate tmux colors from vim statusline
Plug 'neoclide/coc.nvim', {'branch': 'release'} " basically vscode
let g:coc_global_extensions = [
  \ 'coc-emmet',
  \ 'coc-eslint',
  \ 'coc-git',
  \ 'coc-github',
  \ 'coc-json',
  \ 'coc-pairs',
  \ 'coc-prettier',
  \ 'coc-react-refactor',
  \ 'coc-snippets',
  \ 'coc-styled-components',
  \ 'coc-tabnine',
  \ 'coc-tslint',
  \ 'coc-tsserver',
  \ 'https://github.com/rodrigore/coc-tailwind-intellisense',
  \]
set shortmess+=c
set updatetime=300
" Faster python detection
let g:python3_host_prog = system('which python3')[:-2]
" Go to def
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
" Navigate through git changes on file
nmap ) <Plug>(coc-git-nextchunk)
nmap ( <Plug>(coc-git-prevchunk)
nmap <leader>u :CocCommand git.chunkUndo<cr>
" Use K for documentation including Coc
nmap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
" Coc commands and stuff
nmap <silent> ge <Plug>(coc-diagnostic-next-error)
nmap <silent> gE <Plug>(coc-diagnostic-prev-error)
nmap <leader>r <Plug>(coc-rename)
nmap <leader>cc :CocCommand<cr>
nmap <leader>cl :CocList<cr>
nmap <leader>ca :CocAction<cr>
vmap <leader>ca :CocAction<cr>
command! -nargs=? Fold :call CocAction('fold', <f-args>)
" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
" Trigger coc with c-n
inoremap <silent><expr> <c-n> coc#refresh()

"
" End of plugins
"
call plug#end()

" Custom commands
command! ImportES6 :execute "normal! 0ciwimport\<esc>f=hdt'i from \<esc>f)xj0"
command! ConstImport :execute "normal! 0ciwconst\<esc>/from\<cr>ciw= require(\<esc>lxA)\<esc>"
command! MetaResponsiveTag :execute "normal! i<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\<esc>"
command! HotReload autocmd BufWritePost *.vim source %

"
" Color config
set termguicolors
colorscheme xcodedark
