config_version = 14

[shell]
app_icon_colorize = false

[theme.templates]
community_ids = [ "opencode", "zen-browser", "telegram", "neovim", "herdr", "tmux" ]

[wallpaper.default]
path = "/home/pol/.dotfiles/config/wallpapers/fuji.jpg"

[wallpaper.last]
path = "/home/pol/.dotfiles/config/wallpapers/fuji.jpg"

[wallpaper.monitors.DP-3]
path = "/home/pol/.dotfiles/config/wallpapers/fuji.jpg"