vim.loader.enable() -- Enables the experimental Lua module loader

require "pablopunk.plugins-setup"

require "pablopunk.core.abbreviations"
require "pablopunk.core.autocommands"
require "pablopunk.core.colorscheme"
require "pablopunk.core.commands"
require "pablopunk.core.keymaps"
require "pablopunk.core.options"

require "pablopunk.plugins.autopairs"
-- require "pablopunk.plugins.dashboard"
require "pablopunk.plugins.gitsigns"
require "pablopunk.plugins.lazygit"
require "pablopunk.plugins.lsp.lspconfig"
require "pablopunk.plugins.lsp.lspsaga"
require "pablopunk.plugins.lsp.mason"
require "pablopunk.plugins.lsp.null-ls"
require "pablopunk.plugins.lualine"
require "pablopunk.plugins.nvim-cmp"
require "pablopunk.plugins.nvim-tree"
require "pablopunk.plugins.startify"
require "pablopunk.plugins.telescope"
require "pablopunk.plugins.treesitter"
require "pablopunk.plugins.which-key"
