return {
  brew = {
    "1password",
    "alt-tab",
    "arc",
    "cleanshot",
    "hiddenbar",
    "iina",
    "karabiner-elements",
    "latest",
    "missive",
    "notion-calendar",
    "pablopunk/brew/swift-shift",
    "raycast",
    "sf-symbols",
    "spotify",
    "whatsapp",
    "zed",
  },
}
