virtual_modifiers:
  - CapsLock

keymap:
  - name: Caps+hjkl Navigation
    remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right
      CapsLock-q: Mute
      CapsLock-w: VolumeDown
      CapsLock-e: VolumeUp
      CapsLock-a: PreviousSong
      CapsLock-s: PlayPause
      CapsLock-d: NextSong
