;; Kanata configuration for GMMK Pro keyboard

(defcfg
  ;; Linux-specific configuration
  linux-dev /dev/input/by-id/usb-USB_HID_GMMK_PRO-event-kbd
  process-unmapped-keys yes
)

;; Source layer - this defines the keys that will be processed by kanata
(defsrc
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  del
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft      up
  lctl lmet lalt           spc            ralt rmet rctl left down rght
)

;; Define aliases for special keys and actions
(defalias
  ;; Layer aliases
  l1 (layer-toggle layer1)  ;; Caps = Layer1 toggle
  
  ;; Special characters for Spanish keyboard
  lbrk (multi ralt [)  ;; AltGr+[ for left bracket
  rbrk (multi ralt ])  ;; AltGr+] for right bracket
  lbrc (multi ralt ')  ;; AltGr+' for left bracket
  rbrc (multi ralt \)  ;; AltGr+' for right bracket
)

;; Base layer - default behavior
(deflayer base
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  @l1  _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _         _
  _    _    _              _              _    _    _    _    _    _
)

;; Layer1 - activated by holding caps as a modifier
(deflayer layer1
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _   @lbrk @rbrk @lbrc @rbrc     _    _ 
  _    _    _    _    _    _    _   left down up rght  _    _    _ 
  _    _    _    _    _    _    _    _    _    _    _    _         _
  _    _    _              _              _    _    _    _    _    _
)
