[colors]
background = "#2c383aFF"
text_primary = "#f2f3f3FF"
text_muted = "#afb6b6FF"
accent_primary = "#67e4e4FF"
accent_secondary = "#5c99d6FF"
warning = "#6666ccFF"
error = "#fd4663FF"
insert_hint = "#6666cc80"
backdrop = "#232c2eFF"

[colors.border]
focused = "#67e4e4FF"
unfocused = "#232c2eFF"
scratchpad_focused = "#6666ccFF"
scratchpad_unfocused = "#1b1b64FF"
outer = "#1a2123FF"

[colors.overview]
background_tint = "#1a212388"
