[colors]
background = "#222744FF"
text_primary = "#f2f2f3FF"
text_muted = "#afb0b6FF"
accent_primary = "#677be4FF"
accent_secondary = "#865cd6FF"
warning = "#bc66ccFF"
error = "#fd4663FF"
insert_hint = "#bc66cc80"
backdrop = "#1b1f37FF"

[colors.border]
focused = "#677be4FF"
unfocused = "#1b1f37FF"
scratchpad_focused = "#bc66ccFF"
scratchpad_unfocused = "#591b64FF"
outer = "#141829FF"

[colors.overview]
background_tint = "#14182988"
