[colors]
background = "#243c42FF"
text_primary = "#f2f3f3FF"
text_muted = "#afb6b6FF"
accent_primary = "#67dfe4FF"
accent_secondary = "#5c94d6FF"
warning = "#6a66ccFF"
error = "#fd4663FF"
insert_hint = "#6a66cc80"
backdrop = "#1d3035FF"

[colors.border]
focused = "#67dfe4FF"
unfocused = "#1d3035FF"
scratchpad_focused = "#6a66ccFF"
scratchpad_unfocused = "#1e1b64FF"
outer = "#162428FF"

[colors.overview]
background_tint = "#16242888"
