#
# OH-MY-ZSH
#
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git osx npm)
source $ZSH/oh-my-zsh.sh

#
# USER CONFIG
#
source ~/.functions
source ~/.aliases
source ~/.path
# $HOME/.hello| lolcat
F=$HOME/.additional; [ -f $F ] && . $F # aditional local config

#
# PROMPT
#
eval "$(starship init zsh)"

# Vars
export EDITOR=nvim
export SHELL="$(which zsh)"

# Load nvm
alias nvm="unalias nvm; [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"; nvm $@"

# Fix for zlib when installing pip Pillow
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
