#
# OH-MY-ZSH
#
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="intheloop"
plugins=(git osx npm)
source $ZSH/oh-my-zsh.sh

#
# USER CONFIG
#
source ~/.functions
source ~/.aliases
source ~/.path
# $HOME/.hello| lolcat
F=$HOME/.additional; [ -f $F ] && . $F # aditional local config

#
# PROMPT
#
# eval "$(starship init zsh)"

# Use bashy if it exist
# Vars
export EDITOR=nvim
export SHELL="$(which zsh)"

# Fix for zlib when installing pip Pillow
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

# GPG
export GPG_TTY=$(tty)
