#
# OH-MY-ZSH
#
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git osx npm)
source $ZSH/oh-my-zsh.sh

#
# PURE PROMPT
#
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:branch color magenta
zstyle :prompt:pure:path color cyan
prompt pure

#
# USER CONFIG
#
source ~/.functions
source ~/.aliases
source ~/.path
F=$HOME/.hello; [ -f $F ] && . $F
F=$HOME/.additional; [ -f $F ] && . $F # aditional local config

# Vars
export EDITOR=nvim

eval "$(pyenv init -)" # python versions
