#!/usr/bin/env bash

# Configurable path
MAZE_RUNTIME_PATH=~/src/maze/maze-monorepo/.maze-runtime.yaml

# Usage: tt [search]
# Examples:
#   tt shared-components # trigger exact match
#   tt shared webapp     # trigger fuzzy match (multiple services) (select before triggering)
#   tt shard             # trigger fuzzy match (select before triggering)
#   tt                   # select from all items

fzf_short() {
  fzf --height=10 --reverse "$@"
}

all_items=($(awk -F: '/^[[:space:]]{6}[a-zA-Z_-]+/ {print $1}' "$MAZE_RUNTIME_PATH" | sed 's/^[[:space:]]*//'))

trigger_item() {
  tilt enable "$1" && tilt trigger "$1"
}

export -f trigger_item # so it can be used in xargs

select_and_trigger() {
  printf '%s\n' "${all_items[@]}" | fzf_short "$@" | xargs -I {} bash -c 'trigger_item "$@"' _ {}
}

if [[ $# -gt 0 ]]; then
  for arg in "$@"; do
    if [[ " ${all_items[*]} " =~ " $arg " ]]; then
      trigger_item "$arg"
    else
      select_and_trigger -q "$arg"
    fi
  done
else
  select_and_trigger
fi
