onboarding = false

[theme]
name = "terminal"

auto_switch = false
[keys]
prefix = "ctrl+a"
settings = ""
copy_mode = "prefix+y"
split_horizontal = ["prefix+s", "prefix+ctrl+s"]
split_vertical = ["prefix+v", "prefix+ctrl+v"]
focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"
previous_workspace = "ctrl+up"
next_workspace = "ctrl+down"
previous_tab = "ctrl+left"
next_tab = "ctrl+right"
workspace_picker = ""
new_worktree = "prefix+w"
new_workspace = "prefix+shift+w"
rename_workspace = "prefix+r"
resize_mode = ""
reload_config = "prefix+,"

[[keys.command]]
key = "prefix+space"
type = "popup"
command = "hr"
width = "60%"
height = "40%"

[ui]
agent_panel_sort = "priority"
prompt_new_tab_name = false

show_agent_labels_on_pane_borders = true
status_indicators = "symbols"
[ui.toast]
delivery = "system"

[theme.custom]
accent = "#e68b66"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#3e271e"
selection_bg = "#4c3025"
surface0 = "#3e271e"
surface1 = "#4c3025"
surface_dim = "#1c110d"
overlay0 = "#716661"
overlay1 = "#b6b1af"
text = "#f3f2f2"
subtext0 = "#b6b1af"
mauve = "#edac91"
green = "#e68b66"
yellow = "#e3c555"
red = "#e37e55"
blue = "#bae355"
teal = "#edda92"
peach = "#e3c555"
