# git aliases
alias g=git
alias gst='git status'
alias gp='git push'
alias gl='git pull'
alias glog='git log --oneline --decorate --graph'
alias gd='git diff -w'
alias gds='git diff -w --staged'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gck='git checkout'
# ls aliases
alias ll='ls -lagh'
alias la='ls -a1'
alias l='ls -a1'
# other
alias cacl='php app/console ca:cl -e prod && php app/console ca:cl -e dev'
alias vi=vim
alias prof='PS4='"'"'$(gdate "+%s.%N ($LINENO) + ")'"'"' bash -x '

# PATH
export PATH=$PATH:~/.composer/vendor/bin:$HOME/.yarn/bin:$HOME/bin:$HOME/.npm-global/bin

[ "$(uname)" == "Linux" ] && machine="($HOSTNAME) "
if hash bashy 2>/dev/null; then
  export PS1='${machine}$(bashy) '
else
  export PS1='${machine}\W '
fi

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

