# git aliases
alias g=git
alias gst='git status'
alias gp='git push'
alias gl='git pull'
alias glog='git log --oneline --decorate --graph'
# other aliases
alias l='ls -lsah'
alias ll='ls -lsah'

export PATH=$PATH:~/.composer/vendor/bin/:/opt/bin/:$HOME/.yarn/bin/
alias cacl='php app/console ca:cl -e prod && php app/console ca:cl -e dev'
alias vi=vim

[ "$HOSTNAME" == "raspberrypi" ] && machine='(raspberry) '
bold=$(tput bold)
normal=$(tput sgr0)
export PS1='$machine△ \W ${bold}$(vcprompt -f "%b ")${normal}'
