# git aliases
alias g=git
alias gst='git status'
alias gp='git push'
alias gl='git pull'
alias glog='git log --oneline --decorate --graph'
# other aliases
alias l='ls -lsah'
alias ll='ls -lsah'
alias y='yarn'

export PATH=$PATH:~/.composer/vendor/bin/:/opt/bin/:$HOME/.yarn/bin/
alias cacl='php app/console ca:cl -e prod && php app/console ca:cl -e dev'
alias vi=vim

[ "$HOSTNAME" == "raspberrypi" ] && machine='(raspberry) '
if hash gitprompt 2>/dev/null; then
  export PS1='\[${machine}\]△ \[$(gitprompt)\] '
else
  export PS1='\[${machine}\]△ \W '
fi
